source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GeofenceDebugController_Example', :exclusive => true do
  pod 'GeofenceDebugController', :path => '../'
end

target 'GeofenceDebugController_Tests', :exclusive => true do
  pod 'GeofenceDebugController', :path => '../'

  
end
